// Generated by VHDL2SV. Review conversion diagnostics before synthesis.
module array_test
(
    input logic clk,
    input logic rst
);
    typedef logic [15:0] data_array_t [0:5];
    data_array_t a;
    data_array_t b;
    data_array_t c;
    data_array_t d;
    data_array_t e;
    data_array_t f;
    always_ff @(posedge clk) begin : P1
        for (int i = 0; i <= 5; i++) begin
            a[i] <= d[i];
            b[i] <= e[i];
            c[i] <= f[i];
        end
    end
endmodule
