"""Shared traversal and explicit Verilog-family generation (no textual lowering)."""
from collections import defaultdict
from .ir import Expr, Type
from .lex import literal_int
from vhdl2sv.lexer import ParseError


def children(n):
    yield from n.body
    yield from n.data.get('otherwise', [])
    for _, body in n.data.get('choices', []): yield from body


def walk(nodes):
    for n in nodes:
        yield n
        yield from walk(list(children(n)))


def root_name(e):
    while e.kind in ('index','slice','field'): e=e.args[0]
    return e.value if e.kind=='name' else ''


def targets(nodes):
    return {root_name(n.data['target']) for n in walk(nodes) if n.kind=='assignment'}


def sv_expr(e, target='systemverilog', width=None):
    if e is None: return ''
    render=lambda x:sv_expr(x,target)
    k,a,v=e.kind,e.args,e.value
    if k in ('name','literal'):
        if k=='literal' and len(v)==2 and v[0]=="'" and target=='verilog':
            if width is None: raise ParseError('unbased unsized literal requires known destination width for Verilog')
            return '{'+width+"{1'b"+v[1]+'}}'
        return v + (' ' if k=='name' and v.startswith('\\') else '')
    if k=='binary': return '('+render(a[0])+' '+v+' '+render(a[1])+')'
    if k=='unary': return '('+v+render(a[0])+')'
    if k=='conditional': return '('+render(a[0])+' ? '+sv_expr(a[1],target,width)+' : '+sv_expr(a[2],target,width)+')'
    if k=='concat': return '{'+', '.join(map(render,a))+'}'
    if k=='repeat': return '{'+render(a[0])+'{'+', '.join(map(render,a[1].args))+'}}'
    if k=='index': return render(a[0])+'['+render(a[1])+']'
    if k=='slice': return render(a[0])+'['+render(a[1])+':'+render(a[2])+']'
    if k=='field': return render(a[0])+'.'+v
    if k=='call':
        if v not in ('$signed','$unsigned','$clog2'): raise ParseError(f'unsupported function {v}')
        return v+'('+', '.join(map(render,a))+')'
    raise ParseError(f'unsupported expression kind {k}')


def width_of(t):
    if t.kind=='integer': return '32'
    if t.bounds:
        l,r=t.bounds
        try: return str(abs(literal_int(l)-literal_int(r))+1)
        except (ValueError,ZeroDivisionError):
            a,b=sv_expr(l),sv_expr(r)
            return f'(({a}) >= ({b}) ? ({a})-({b})+1 : ({b})-({a})+1)'
    return '1'


class VerilogGenerator:
    def __init__(self,target='systemverilog'): self.target=target
    def expr(self,e,width=None): return sv_expr(e,self.target,width)
    @staticmethod
    def indent(lines): return ['    '+l for l in lines]
    def typ(self,t,base):
        if t.dimensions: raise ParseError('unpacked array declarations require array lowering; unsupported in this target subset')
        if t.enum and self.target=='systemverilog': return t.enum
        if t.kind=='integer': return 'integer'
        signed=' signed' if t.signed else ''
        bounds=' ['+':'.join(self.expr(e) for e in t.bounds)+']' if t.bounds else ''
        return base+signed+bounds
    def declaration(self,d,procedural):
        if d.kind in ('parameter','localparam'):
            if d.value is None: raise ParseError('parameter default required')
            typ=self.typ(d.type,'').strip()
            if d.type.kind=='bits' and not d.type.bounds: typ=''
            return d.kind+' '+(typ+' ' if typ else '')+d.name+' = '+self.expr(d.value,width_of(d.type))
        base=('reg' if d.name in procedural else 'wire') if self.target=='verilog' else ('wire' if d.net or d.direction=='inout' else 'logic')
        if d.direction in ('input','inout') and d.name in procedural: raise ParseError('procedural assignment to input/inout port')
        prefix=d.direction+' ' if d.direction else ''
        value=' = '+self.expr(d.value,width_of(d.type)) if d.value else ''
        return prefix+self.typ(d.type,base)+' '+d.name+value
    def generate(self,design):
        out=['// Generated by HDL Converter. Review all WARNING/TODO comments.']
        for m in design.modules:
            self.module=m
            self.symbols={d.name:d.type for d in m.ports+m.declarations+m.parameters}
            owners=defaultdict(set); procedural=set(); continuous=set()
            for n in walk(m.statements):
                if n.kind=='process':
                    for name in targets(n.body): owners[name].add(id(n)); procedural.add(name)
                if n.kind=='assignment' and n.data['concurrent']: continuous.add(root_name(n.data['target']))
            self.owners=owners
            if procedural & continuous: raise ParseError('mixed continuous and procedural drivers: '+', '.join(sorted(procedural & continuous)))
            header='module '+m.name
            if m.parameters: header+=' #(\n'+',\n'.join(self.indent([self.declaration(d,procedural) for d in m.parameters]))+'\n)'
            out += [header+' (']+self.indent([',\n    '.join(self.declaration(d,procedural) for d in m.ports)])+[');']
            for name,(t,values) in m.enums.items():
                if self.target=='systemverilog':
                    out += self.indent(['typedef enum '+self.typ(t,'logic')+' {'+', '.join(n+' = '+self.expr(e) for n,e in values)+'} '+name+';'])
                else:
                    out += self.indent(['localparam '+self.typ(t,'').strip()+' '+n+' = '+self.expr(e,width_of(t))+';' for n,e in values])
            out+=self.indent([self.declaration(d,procedural)+';' for d in m.declarations])
            out+=self.indent(self.statements(m.statements))+['endmodule','']
        return '\n'.join(out)+'\n'
    def statements(self,nodes,context='concurrent'):
        out=[]
        for n in nodes:
            d=n.data;k=n.kind
            if k=='assignment':
                name=root_name(d['target']); typ=self.symbols.get(name,Type())
                width=width_of(typ)
                if d['target'].kind=='index': width='1'
                elif d['target'].kind=='slice': width=width_of(Type(bounds=tuple(d['target'].args[1:])))
                out.append(('assign ' if d['concurrent'] else '')+self.expr(d['target'])+' '+d['op']+' '+self.expr(d['value'],width)+';')
            elif k=='block':
                out+=['begin'+(' : '+n.label if n.label else '')]+self.indent(self.statements(n.body,context))+['end']
            elif k=='process':
                events=d['events']; flavor='always'
                if self.target=='systemverilog':
                    # Modernize only when ownership is unambiguous. Level-list
                    # always is kept because always_comb has different semantics.
                    unique=all(len(self.owners[name])==1 for name in targets(n.body))
                    if unique and events and all(x.data['op']=='<=' for x in walk(n.body) if x.kind=='assignment'): flavor='always_ff'
                    elif d['flavor'] in ('always_comb','always_latch'): flavor=d['flavor']
                sensitivity=''
                if flavor not in ('always_comb','always_latch'):
                    sensitivity=' @('+(' or '.join(edge+' '+name for edge,name in events) if events else ('*' if not d['sensitivity'] or d['sensitivity']==['*'] else ' or '.join(d['sensitivity'])))+')'
                out += [flavor+sensitivity+' begin']+self.indent(self.statements(n.body,'process'))+['end']
            elif k=='if':
                out+=['if ('+self.expr(d['condition'])+') begin']+self.indent(self.statements(n.body,context))+['end']
                if d['otherwise']: out[-1]+=' else begin'; out+=self.indent(self.statements(d['otherwise'],context))+['end']
            elif k=='case':
                out+=['case ('+self.expr(d['expression'])+')']
                for values,body in d['choices']:
                    out+=self.indent([(', '.join(self.expr(e) for e in values) if values else 'default')+': begin']+self.indent(self.statements(body,context))+['end'])
                out+=['endcase']
            elif k=='for':
                name=d['name']; generate=d['generate']
                declaration='genvar ' if generate else 'int '
                if self.target=='verilog':
                    out += ['begin : loop_'+name, '    '+('genvar' if generate else 'integer')+' '+name+';']
                    declaration=''
                out += ['for ('+declaration+name+' = '+self.expr(d['start'])+'; '+self.expr(d['condition'])+'; '+name+' = '+self.expr(d['update'])+') begin : iter_'+name]+self.indent(self.statements(n.body,context))+['end']
                if self.target=='verilog': out+=['end']
            elif k=='generate': out+=['generate']+self.indent(self.statements(n.body))+['endgenerate']
            elif k=='instance':
                mapping=lambda pairs:', '.join(('.'+name+'('+self.expr(e)+')') if name else self.expr(e) for name,e in pairs)
                params=' #('+mapping(d['parameters'])+')' if d['parameters'] else ''
                out+=[d['module']+params+' '+d['name']+' ('+mapping(d['ports'])+');']
            elif k=='declaration':
                for decl in d['declarations']:
                    self.symbols[decl.name]=decl.type
                    out.append(self.typ(decl.type,'reg' if self.target=='verilog' else 'logic')+' '+decl.name+(' = '+self.expr(decl.value,width_of(decl.type)) if decl.value else '')+';')
            else: raise ParseError('unsupported statement '+k)
        return out
